version: '3'

services:
  database:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_PASSWORD=redhat
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=redhat

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - nextcloud:/var/www/html
    networks:
      - mynet
    restart: always

volumes:
  nextcloud:
  db:
networks:
  mynet:
